### ISSUE TITLE
About IMU Calibration

### ISSUE THREAD

**Issue by lidarmansiwon** [LimHaeryong/eskf-gnss-imu-localization#2]
Hello, thanks to the good package, I've taken a good look at it, but I just have a few questions, so I'm posting it like this

This package contains functions that are predicted by IMU and updated to GNSS. In this process, I wonder if only GNSS is corrected with IMU data? Or if IMU data is also corrected. The reason for asking is that both my IMU and GPS have a lot of errors, so I wonder if they correct the  accumulated error of IMU well.

**Comment by LimHaeryong** [comment]
Hello, siwon 

In Imu process method, it contains Propagation of P matrix(covariance of error state). So if we processing imu more, P matrix gets bigger. And when we update gnss data, state is updated so that the P matrix is minimized. 

So imu, gnss data are both used to estimate state and P. They don't correct data themselves

**Comment by lidarmansiwon** [comment]
Thank you for your kind reply!
